from enum import Enum

class ClassifierType(str, Enum):
    # Classification
    LOGISTIC_CLASSIFIER = "LOGISTIC_CLASSIFIER"
    MULTILAYER_PERCEPTRON_CLASSIFIER = "MULTILAYER_PERCEPTRON_CLASSIFIER"
    DECISION_TREE_CLASSIFIER = "DECISION_TREE_CLASSIFIER"

    # Regression
    LINEAR_REGRESSOR = "LINEAR_REGRESSOR"
    LASSO_REGRESSOR = "LASSO_REGRESSOR"
    RIDGE_REGRESSOR = "RIDGE_REGRESSOR"
    ELASTIC_NETWORK_REGRESSOR = "ELASTIC_NETWORK_REGRESSOR"
    KNN_REGRESSOR = "KNN_REGRESSOR"
    LINEAR_SUPPORT_VECTOR_MACHINE = "LINEAR_SUPPORT_VECTOR_MACHINE"
    DECISION_TREE_REGRESSOR = "DECISION_TREE_REGRESSOR"
    RANDOM_FOREST_REGRESSOR = "RANDOM_FOREST_REGRESSOR"
    MULTILAYER_PERCEPTRON_REGRESSOR = "MULTILAYER_PERCEPTRON_REGRESSOR"
